name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@a801b411369e4686427b4d054b0cef92cf074e2a # main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@a801b411369e4686427b4d054b0cef92cf074e2a # main

  eslint-lint-check:
    name: ESLint Check
    uses: bymbly/gha-workflows/.github/workflows/eslint-lint-check.yaml@a801b411369e4686427b4d054b0cef92cf074e2a # main

  npm-test:
    name: npm Test
    uses: bymbly/gha-workflows/.github/workflows/npm-test.yaml@a801b411369e4686427b4d054b0cef92cf074e2a # main

  publish-npm-package:
    name: Publish NPM Package
    needs:
      [prettier-format-check, markdown-lint-check, eslint-lint-check, npm-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write # required for OIDC publishing
    uses: bymbly/gha-workflows/.github/workflows/npm-semantic-release.yaml@a801b411369e4686427b4d054b0cef92cf074e2a # main
    with:
      registry-url: "https://registry.npmjs.org/"
